import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  TextRun,
  WidthType,
  ImageRun,
  AlignmentType,
  VerticalAlign,
  BorderStyle,
} from 'docx';
import { BackendTest, BackendBranding } from './types';
import { api, API_ORIGIN } from './api';

const DEFAULT_BRANDING: BackendBranding = {
  primaryColor: '#4f46e5',
  footerText: 'Generated by AI Website QA Engineer',
  headerText: 'AI QA Engineer',
  headerFontSize: 16,
  footerFontSize: 8,
  logoWidth: 84,
  logoHeight: 54,
  logoUrl: null,
  updatedAt: null,
};

// jsPDF's default document unit is mm; branding logo dimensions are stored
// in px (the intuitive unit for sizing an image) and converted here.
const PX_TO_MM = 25.4 / 96;

// Reports are white-labeled with whatever the workspace has configured in
// Settings → White-label Reports. Falls back to sane defaults if the
// backend is unreachable so exports never hard-fail on this. Exported so
// every export path in the app (not just this file's own PDF/CSV/DOCX
// builders) can pull the same branding.
export async function fetchBrandingSafe(): Promise<BackendBranding> {
  try {
    return await api.branding.get();
  } catch {
    return DEFAULT_BRANDING;
  }
}

export interface LogoAsset {
  dataUrl: string;
  bytes: ArrayBuffer;
  type: 'png' | 'jpg';
  width: number;
  height: number;
}

/**
 * Fetches the branding logo and returns it in every shape a document builder
 * might need: a data URL (jsPDF#addImage), raw bytes (docx ImageRun), and
 * its natural pixel size (so callers can scale it without distorting the
 * aspect ratio). Returns null if there's no logo configured, the fetch
 * fails, or the file isn't a raster format jsPDF/docx can embed directly
 * (SVG logos are skipped rather than half-rendered) — every caller must
 * treat null as "just skip the logo," never as an error.
 */
export async function fetchLogoAsset(logoUrl: string | null): Promise<LogoAsset | null> {
  if (!logoUrl) return null;
  try {
    const res = await fetch(`${API_ORIGIN}${logoUrl}`);
    if (!res.ok) return null;
    const blob = await res.blob();
    if (!/png|jpe?g/i.test(blob.type)) return null;
    const type: 'png' | 'jpg' = /png/i.test(blob.type) ? 'png' : 'jpg';

    const bytes = await blob.arrayBuffer();
    const dataUrl = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(new Error('logo read failed'));
      reader.readAsDataURL(blob);
    });
    const { width, height } = await new Promise<{ width: number; height: number }>((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ width: img.naturalWidth || 1, height: img.naturalHeight || 1 });
      img.onerror = () => resolve({ width: 1, height: 1 });
      img.src = dataUrl;
    });

    return { dataUrl, bytes, type, width, height };
  } catch {
    return null;
  }
}

/** Fit `logo` inside a maxW×maxH box (mm, px, whatever unit the caller uses) without distorting its aspect ratio. */
export function fitLogoBox(logo: LogoAsset, maxW: number, maxH: number): { w: number; h: number } {
  let w = maxW;
  let h = (logo.height / logo.width) * w;
  if (h > maxH) {
    h = maxH;
    w = (logo.width / logo.height) * h;
  }
  return { w, h };
}

function hexToRgb(hex: string): [number, number, number] {
  const match = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!match) return [79, 70, 229];
  return [parseInt(match[1], 16), parseInt(match[2], 16), parseInt(match[3], 16)];
}

function slug(url: string) {
  return url
    .replace(/^https?:\/\//, '')
    .replace(/[^a-z0-9]+/gi, '-')
    .toLowerCase()
    .replace(/(^-|-$)/g, '')
    .slice(0, 60);
}

function downloadBlobObject(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadText(content: string, filename: string, mime: string) {
  downloadBlobObject(new Blob([content], { type: mime }), filename);
}

// ---------------------------------------------------------------------------
// CSV
// ---------------------------------------------------------------------------
export async function exportReportCSV(test: BackendTest) {
  const branding = await fetchBrandingSafe();
  const esc = (v: unknown) => `"${String(v ?? '-').replace(/"/g, '""')}"`;
  const lines: string[] = [];

  lines.push(`${branding.headerText} - Report for ${test.url}`);
  lines.push(`Generated,${new Date().toLocaleString()}`);
  lines.push(`Overall Score,${test.score ?? '-'}`);
  lines.push(`Status,${test.status}`);
  lines.push('');

  lines.push('Lighthouse Scores');
  lines.push('Category,Score');
  lines.push(`Performance,${test.scores.performance ?? '-'}`);
  lines.push(`Accessibility,${test.scores.accessibility ?? '-'}`);
  lines.push(`SEO,${test.scores.seo ?? '-'}`);
  lines.push(`Best Practices,${test.scores.bestPractices ?? '-'}`);
  lines.push('');

  if (test.accessibility?.violations?.length) {
    lines.push('Accessibility Violations');
    lines.push('Impact,Issue,Elements Affected,Help URL');
    test.accessibility.violations.forEach((v) => {
      lines.push([esc(v.impact), esc(v.help), esc(v.nodes), esc(v.helpUrl)].join(','));
    });
    lines.push('');
  }

  if (test.seo?.checks?.length) {
    lines.push(`SEO Audit (score ${test.seo.score ?? '-'}/100)`);
    lines.push('Check,Status,Message');
    test.seo.checks.forEach((c) => {
      lines.push([esc(c.id), esc(c.passed ? 'Pass' : 'Fail'), esc(c.message)].join(','));
    });
    lines.push('');
  }

  if (test.visualRegression?.length) {
    lines.push('Visual Regression');
    lines.push('Viewport,Status,Diff %');
    test.visualRegression.forEach((r) => {
      lines.push(
        [
          esc(r.viewport),
          esc(r.isNewBaseline ? 'New baseline' : r.significant ? 'Significant change' : 'No change'),
          esc(r.diffPercentage ?? 0),
        ].join(',')
      );
    });
    lines.push('');
  }

  if (test.crossBrowser?.length) {
    lines.push('Cross-Browser Testing');
    lines.push('Browser,Status,Load Time (ms),Detail');
    test.crossBrowser.forEach((r) => {
      lines.push(
        [
          esc(r.browser),
          esc(r.ok ? 'OK' : 'Failed'),
          esc(r.loadTimeMs ?? '-'),
          esc(r.error || (r.statusCode ? `Status ${r.statusCode}` : '-')),
        ].join(',')
      );
    });
    lines.push('');
  }

  if (test.performanceBenchmark) {
    lines.push('Performance Benchmark');
    lines.push('Metric,Current,Previous,Delta');
    const pb = test.performanceBenchmark;
    (Object.keys(pb.metrics) as Array<keyof typeof pb.metrics>).forEach((key) => {
      lines.push(
        [esc(key), esc(pb.metrics[key]), esc(pb.previousMetrics?.[key] ?? '-'), esc(pb.delta[key] ?? '-')].join(',')
      );
    });
    lines.push('');
  }

  if (test.issues?.length) {
    lines.push('All Issues');
    lines.push('Severity,Category,Title,Description,URL,Resolved');
    test.issues.forEach((i) => {
      lines.push(
        [esc(i.severity), esc(i.category), esc(i.title), esc(i.description), esc(i.url), esc(i.resolved ? 'Yes' : 'No')].join(
          ','
        )
      );
    });
  }

  lines.push('');
  lines.push(branding.footerText);

  downloadText(lines.join('\n'), `qa-report-${slug(test.url)}.csv`, 'text/csv');
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------
export async function exportReportPDF(test: BackendTest) {
  const branding = await fetchBrandingSafe();
  const logo = await fetchLogoAsset(branding.logoUrl);
  const brandRgb = hexToRgb(branding.primaryColor);
  const doc = new jsPDF();
  const marginX = 14;
  const pageWidth = doc.internal.pageSize.getWidth();

  // ---- Header band: logo left, header text right, divider below ----
  let logoHmm = 0;
  if (logo) {
    const wMm = branding.logoWidth * PX_TO_MM;
    const hMm = branding.logoHeight * PX_TO_MM;
    doc.addImage(logo.dataUrl, logo.type.toUpperCase(), marginX, 8, wMm, hMm);
    logoHmm = hMm;
  }

  const headerFontMm = branding.headerFontSize * 0.3528; // pt -> mm
  doc.setFontSize(branding.headerFontSize);
  doc.setTextColor(brandRgb[0], brandRgb[1], brandRgb[2]);
  doc.text(branding.headerText, pageWidth - marginX, 8 + Math.max(logoHmm, headerFontMm) / 2 + headerFontMm / 3, {
    align: 'right',
  });

  const dividerY = 8 + Math.max(logoHmm, headerFontMm) + 5;
  doc.setDrawColor(brandRgb[0], brandRgb[1], brandRgb[2]);
  doc.setLineWidth(0.4);
  doc.line(marginX, dividerY, pageWidth - marginX, dividerY);

  let y = dividerY + 8;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(test.url, marginX, y);
  y += 5;
  doc.text(`Generated: ${new Date().toLocaleString()}`, marginX, y);
  y += 5;
  doc.text(`Overall Score: ${test.score ?? '-'} / 100  |  Status: ${test.status}`, marginX, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Score']],
    body: [
      ['Performance', String(test.scores.performance ?? '-')],
      ['Accessibility', String(test.scores.accessibility ?? '-')],
      ['SEO', String(test.scores.seo ?? '-')],
      ['Best Practices', String(test.scores.bestPractices ?? '-')],
    ],
    theme: 'grid',
    headStyles: { fillColor: brandRgb },
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;

  const ensureSpace = () => {
    if (y > 260) {
      doc.addPage();
      y = 16;
    }
  };

  if (test.accessibility?.violations?.length) {
    ensureSpace();
    doc.setFontSize(12);
    doc.setTextColor(20);
    doc.text('Accessibility Violations', 14, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [['Impact', 'Issue', 'Elements']],
      body: test.accessibility.violations.map((v) => [v.impact || '-', v.help, String(v.nodes)]),
      theme: 'striped',
      headStyles: { fillColor: brandRgb },
      styles: { fontSize: 8 },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (test.seo?.checks?.length) {
    ensureSpace();
    doc.setFontSize(12);
    doc.text(`SEO Audit (score ${test.seo.score ?? '-'}/100)`, 14, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [['Check', 'Status', 'Message']],
      body: test.seo.checks.map((c) => [c.id, c.passed ? 'Pass' : 'Fail', c.message]),
      theme: 'striped',
      headStyles: { fillColor: brandRgb },
      styles: { fontSize: 8 },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (test.crossBrowser?.length) {
    ensureSpace();
    doc.setFontSize(12);
    doc.text('Cross-Browser Testing', 14, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [['Browser', 'Status', 'Load Time', 'Detail']],
      body: test.crossBrowser.map((r) => [
        r.browser,
        r.ok ? 'OK' : 'Failed',
        r.loadTimeMs ? `${r.loadTimeMs}ms` : '-',
        r.error || (r.statusCode ? `Status ${r.statusCode}` : '-'),
      ]),
      theme: 'striped',
      headStyles: { fillColor: brandRgb },
      styles: { fontSize: 8 },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (test.visualRegression?.length) {
    ensureSpace();
    doc.setFontSize(12);
    doc.text('Visual Regression', 14, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [['Viewport', 'Status', 'Diff %']],
      body: test.visualRegression.map((r) => [
        r.viewport,
        r.isNewBaseline ? 'New baseline' : r.significant ? 'Significant change' : 'No change',
        String(r.diffPercentage ?? 0),
      ]),
      theme: 'striped',
      headStyles: { fillColor: brandRgb },
      styles: { fontSize: 8 },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (test.issues?.length) {
    ensureSpace();
    doc.setFontSize(12);
    doc.text('All Issues', 14, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [['Severity', 'Category', 'Title']],
      body: test.issues.map((i) => [i.severity, i.category, i.title]),
      theme: 'striped',
      headStyles: { fillColor: brandRgb },
      styles: { fontSize: 8 },
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(brandRgb[0], brandRgb[1], brandRgb[2]);
    doc.setLineWidth(0.3);
    doc.line(marginX, 284, pageWidth - marginX, 284);
    doc.setFontSize(branding.footerFontSize);
    doc.setTextColor(150);
    doc.text(branding.footerText, marginX, 290);
  }

  doc.save(`qa-report-${slug(test.url)}.pdf`);
}

// ---------------------------------------------------------------------------
// Word (.docx)
// ---------------------------------------------------------------------------
function makeTable(headers: string[], rows: string[][]) {
  const headerRow = new TableRow({
    children: headers.map(
      (h) =>
        new TableCell({
          width: { size: 100 / headers.length, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })],
        })
    ),
  });
  const bodyRows = rows.map(
    (r) =>
      new TableRow({
        children: r.map(
          (cell) =>
            new TableCell({
              width: { size: 100 / headers.length, type: WidthType.PERCENTAGE },
              children: [new Paragraph(cell)],
            })
        ),
      })
  );
  return new Table({ rows: [headerRow, ...bodyRows], width: { size: 100, type: WidthType.PERCENTAGE } });
}

export async function exportReportDocx(test: BackendTest) {
  const branding = await fetchBrandingSafe();
  const logo = await fetchLogoAsset(branding.logoUrl);
  const brandColorHex = branding.primaryColor.replace(/^#/, '');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const children: any[] = [];

  // ---- Header band: logo left, header text right, borderless table so it reads as one row ----
  const NO_BORDER = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  children.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: NO_BORDER,
        bottom: NO_BORDER,
        left: NO_BORDER,
        right: NO_BORDER,
        insideHorizontal: NO_BORDER,
        insideVertical: NO_BORDER,
      },
      rows: [
        new TableRow({
          children: [
            new TableCell({
              width: { size: 50, type: WidthType.PERCENTAGE },
              verticalAlign: VerticalAlign.CENTER,
              children: logo
                ? [
                    new Paragraph({
                      children: [
                        new ImageRun({
                          type: logo.type,
                          data: logo.bytes,
                          transformation: { width: branding.logoWidth, height: branding.logoHeight },
                        }),
                      ],
                    }),
                  ]
                : [new Paragraph({ text: '' })],
            }),
            new TableCell({
              width: { size: 50, type: WidthType.PERCENTAGE },
              verticalAlign: VerticalAlign.CENTER,
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [
                    new TextRun({
                      text: branding.headerText,
                      bold: true,
                      size: branding.headerFontSize * 2,
                      color: brandColorHex,
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      ],
    })
  );
  // Divider line under the header band
  children.push(
    new Paragraph({
      text: '',
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: brandColorHex, space: 4 } },
    })
  );
  children.push(new Paragraph({ text: '' }));

  children.push(new Paragraph({ text: test.url }));
  children.push(new Paragraph({ text: `Generated: ${new Date().toLocaleString()}` }));
  children.push(new Paragraph({ text: `Overall Score: ${test.score ?? '-'} / 100  |  Status: ${test.status}` }));
  children.push(new Paragraph({ text: '' }));

  children.push(new Paragraph({ text: 'Lighthouse Scores', heading: HeadingLevel.HEADING_2 }));
  children.push(
    makeTable(
      ['Category', 'Score'],
      [
        ['Performance', String(test.scores.performance ?? '-')],
        ['Accessibility', String(test.scores.accessibility ?? '-')],
        ['SEO', String(test.scores.seo ?? '-')],
        ['Best Practices', String(test.scores.bestPractices ?? '-')],
      ]
    )
  );
  children.push(new Paragraph({ text: '' }));

  if (test.accessibility?.violations?.length) {
    children.push(new Paragraph({ text: 'Accessibility Violations', heading: HeadingLevel.HEADING_2 }));
    children.push(
      makeTable(
        ['Impact', 'Issue', 'Elements'],
        test.accessibility.violations.map((v) => [v.impact || '-', v.help, String(v.nodes)])
      )
    );
    children.push(new Paragraph({ text: '' }));
  }

  if (test.seo?.checks?.length) {
    children.push(
      new Paragraph({ text: `SEO Audit (score ${test.seo.score ?? '-'}/100)`, heading: HeadingLevel.HEADING_2 })
    );
    children.push(
      makeTable(
        ['Check', 'Status', 'Message'],
        test.seo.checks.map((c) => [c.id, c.passed ? 'Pass' : 'Fail', c.message])
      )
    );
    children.push(new Paragraph({ text: '' }));
  }

  if (test.crossBrowser?.length) {
    children.push(new Paragraph({ text: 'Cross-Browser Testing', heading: HeadingLevel.HEADING_2 }));
    children.push(
      makeTable(
        ['Browser', 'Status', 'Load Time', 'Detail'],
        test.crossBrowser.map((r) => [
          r.browser,
          r.ok ? 'OK' : 'Failed',
          r.loadTimeMs ? `${r.loadTimeMs}ms` : '-',
          r.error || (r.statusCode ? `Status ${r.statusCode}` : '-'),
        ])
      )
    );
    children.push(new Paragraph({ text: '' }));
  }

  if (test.visualRegression?.length) {
    children.push(new Paragraph({ text: 'Visual Regression', heading: HeadingLevel.HEADING_2 }));
    children.push(
      makeTable(
        ['Viewport', 'Status', 'Diff %'],
        test.visualRegression.map((r) => [
          r.viewport,
          r.isNewBaseline ? 'New baseline' : r.significant ? 'Significant change' : 'No change',
          String(r.diffPercentage ?? 0),
        ])
      )
    );
    children.push(new Paragraph({ text: '' }));
  }

  if (test.issues?.length) {
    children.push(new Paragraph({ text: 'All Issues', heading: HeadingLevel.HEADING_2 }));
    children.push(makeTable(['Severity', 'Category', 'Title'], test.issues.map((i) => [i.severity, i.category, i.title])));
  }

  children.push(new Paragraph({ text: '' }));
  children.push(
    new Paragraph({
      // Divider line above the footer
      border: { top: { style: BorderStyle.SINGLE, size: 6, color: brandColorHex, space: 4 } },
      children: [
        new TextRun({ text: branding.footerText, italics: true, color: '888888', size: branding.footerFontSize * 2 }),
      ],
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  downloadBlobObject(blob, `qa-report-${slug(test.url)}.docx`);
}

// ---------------------------------------------------------------------------
// Ticket list (Issue Tracker) — a scoped list of tickets (e.g. everything for
// one selected site), not a full scan report. Kept deliberately decoupled
// from team-member types: callers pre-resolve `assignees` into a display
// string so this module doesn't need to know about BackendTeamMember.
// ---------------------------------------------------------------------------
export interface TicketExportRow {
  repId: string;
  title: string;
  severity: string;
  category: string;
  status: string; // 'Open' | 'Resolved'
  assignees: string; // pre-joined names, or 'Unassigned'
  url: string;
}

export async function exportTicketListCSV(rows: TicketExportRow[], scopeLabel: string) {
  const branding = await fetchBrandingSafe();
  const esc = (v: unknown) => `"${String(v ?? '-').replace(/"/g, '""')}"`;
  const lines: string[] = [];

  lines.push(`${branding.headerText} - Tickets (${scopeLabel})`);
  lines.push(`Generated,${new Date().toLocaleString()}`);
  lines.push(`Total Tickets,${rows.length}`);
  lines.push('');
  lines.push('Ticket #,Title,Severity,Category,Status,Assigned To,URL');
  rows.forEach((r) => {
    lines.push([esc(r.repId), esc(r.title), esc(r.severity), esc(r.category), esc(r.status), esc(r.assignees), esc(r.url)].join(','));
  });
  lines.push('');
  lines.push(branding.footerText);

  downloadText(lines.join('\n'), `tickets-${slug(scopeLabel)}.csv`, 'text/csv');
}

export async function exportTicketListPDF(rows: TicketExportRow[], scopeLabel: string) {
  const branding = await fetchBrandingSafe();
  const logo = await fetchLogoAsset(branding.logoUrl);
  const brandRgb = hexToRgb(branding.primaryColor);
  const doc = new jsPDF();
  const marginX = 14;
  const pageWidth = doc.internal.pageSize.getWidth();

  let logoHmm = 0;
  if (logo) {
    const wMm = branding.logoWidth * PX_TO_MM;
    const hMm = branding.logoHeight * PX_TO_MM;
    doc.addImage(logo.dataUrl, logo.type.toUpperCase(), marginX, 8, wMm, hMm);
    logoHmm = hMm;
  }

  const headerFontMm = branding.headerFontSize * 0.3528;
  doc.setFontSize(branding.headerFontSize);
  doc.setTextColor(brandRgb[0], brandRgb[1], brandRgb[2]);
  doc.text(branding.headerText, pageWidth - marginX, 8 + Math.max(logoHmm, headerFontMm) / 2 + headerFontMm / 3, {
    align: 'right',
  });

  const dividerY = 8 + Math.max(logoHmm, headerFontMm) + 5;
  doc.setDrawColor(brandRgb[0], brandRgb[1], brandRgb[2]);
  doc.setLineWidth(0.4);
  doc.line(marginX, dividerY, pageWidth - marginX, dividerY);

  let y = dividerY + 8;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Tickets — ${scopeLabel}`, marginX, y);
  y += 5;
  doc.text(`Generated: ${new Date().toLocaleString()}  |  Total: ${rows.length}`, marginX, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    head: [['Ticket #', 'Title', 'Severity', 'Category', 'Status', 'Assigned To']],
    body: rows.map((r) => [r.repId, r.title, r.severity, r.category, r.status, r.assignees]),
    theme: 'striped',
    headStyles: { fillColor: brandRgb },
    styles: { fontSize: 8 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(brandRgb[0], brandRgb[1], brandRgb[2]);
    doc.setLineWidth(0.3);
    doc.line(marginX, 284, pageWidth - marginX, 284);
    doc.setFontSize(branding.footerFontSize);
    doc.setTextColor(150);
    doc.text(branding.footerText, marginX, 290);
  }

  doc.save(`tickets-${slug(scopeLabel)}.pdf`);
}

// ---------------------------------------------------------------------------
// Assigned tickets — one row per assignee (a ticket with two assignees
// appears twice) so "who owns line 42" is a straight lookup, not a CSV cell
// with a comma-joined list to parse.
// ---------------------------------------------------------------------------
export interface AssignedTicketExportRow {
  sNo: number;
  website: string;
  repId: string; // Bug ID
  ticketUrl: string; // deep link back into the app for the "Ticket Link" hyperlink column
  title: string;
  assignedTo: string;
  severity: string; // 'critical' | 'high' | 'medium' | 'low'
  status: string; // 'Open' | 'Resolved'
}

/**
 * Renders a plain pie chart to a PNG buffer via <canvas> — exceljs (used for
 * the styled Excel export below) can't create native Excel chart objects in
 * the browser, only embed images, so the "graph" is a picture, not a live
 * chart. Good enough for a report; not editable in Excel afterward.
 */
function drawPieChartPNG(
  slices: { label: string; value: number; color: string }[],
  size = 340
): Promise<ArrayBuffer> {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  ctx.clearRect(0, 0, size, size);

  const total = slices.reduce((s, d) => s + d.value, 0) || 1;
  const cx = size / 2;
  const cy = size / 2;
  const r = size / 2 - 12;
  let start = -Math.PI / 2;

  slices.forEach((s) => {
    const angle = (s.value / total) * Math.PI * 2;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.arc(cx, cy, r, start, start + angle);
    ctx.closePath();
    ctx.fillStyle = s.color;
    ctx.fill();
    ctx.strokeStyle = '#ffffff';
    ctx.lineWidth = 2;
    ctx.stroke();
    start += angle;
  });

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) return reject(new Error('chart render failed'));
      blob.arrayBuffer().then(resolve).catch(reject);
    }, 'image/png');
  });
}

/** Simple vertical bar chart with y-axis gridlines/ticks and x-axis labels — same "picture, not a live chart" caveat as drawPieChartPNG. */
function drawBarChartPNG(bars: { label: string; value: number; color: string }[], width = 380, height = 260): Promise<ArrayBuffer> {
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d')!;
  ctx.clearRect(0, 0, width, height);

  const padL = 34;
  const padB = 24;
  const padT = 10;
  const padR = 10;
  const plotW = width - padL - padR;
  const plotH = height - padT - padB;
  const maxVal = Math.max(1, ...bars.map((b) => b.value));
  const niceMax = Math.ceil(maxVal / 5) * 5 || 5;

  // Gridlines + y-axis ticks
  ctx.strokeStyle = '#E5E7EB';
  ctx.fillStyle = '#6B7280';
  ctx.font = '10px Arial';
  ctx.textAlign = 'right';
  ctx.textBaseline = 'middle';
  for (let i = 0; i <= 5; i++) {
    const val = (niceMax / 5) * i;
    const y = padT + plotH - (val / niceMax) * plotH;
    ctx.beginPath();
    ctx.moveTo(padL, y);
    ctx.lineTo(width - padR, y);
    ctx.stroke();
    ctx.fillText(String(Math.round(val)), padL - 6, y);
  }

  // Axes
  ctx.strokeStyle = '#9CA3AF';
  ctx.beginPath();
  ctx.moveTo(padL, padT);
  ctx.lineTo(padL, padT + plotH);
  ctx.lineTo(width - padR, padT + plotH);
  ctx.stroke();

  // Bars
  const slot = plotW / bars.length;
  const barW = slot * 0.5;
  ctx.textAlign = 'center';
  bars.forEach((b, i) => {
    const barH = (b.value / niceMax) * plotH;
    const x = padL + i * slot + (slot - barW) / 2;
    const y = padT + plotH - barH;
    ctx.fillStyle = b.color;
    ctx.fillRect(x, y, barW, barH);
    ctx.fillStyle = '#374151';
    ctx.font = 'bold 10px Arial';
    ctx.fillText(b.label, x + barW / 2, padT + plotH + 14);
  });

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) return reject(new Error('chart render failed'));
      blob.arrayBuffer().then(resolve).catch(reject);
    }, 'image/png');
  });
}

export async function exportAssignedTicketsCSV(rows: AssignedTicketExportRow[], scopeLabel: string) {
  const branding = await fetchBrandingSafe();
  const esc = (v: unknown) => `"${String(v ?? '-').replace(/"/g, '""')}"`;
  const lines: string[] = [];

  lines.push(`${branding.headerText} - Bug Tracker (${scopeLabel})`);
  lines.push(`Generated,${new Date().toLocaleString()}`);
  lines.push(`Total Assigned,${rows.length}`);
  lines.push('');
  lines.push('S.No,Website,Bug ID,Ticket Link,Bug Title,Assigned To,Priority,Status');
  rows.forEach((r) => {
    lines.push(
      [esc(r.sNo), esc(r.website), esc(r.repId), esc(r.ticketUrl), esc(r.title), esc(r.assignedTo), esc(PRIORITY_LABEL[r.severity] || r.severity), esc(r.status)].join(',')
    );
  });
  lines.push('');
  lines.push(branding.footerText);

  downloadText(lines.join('\n'), `bug-tracker-${slug(scopeLabel)}.csv`, 'text/csv');
}

const PRIORITY_ORDER = ['critical', 'high', 'medium', 'low'];
const PRIORITY_LABEL: Record<string, string> = { critical: 'P1', high: 'P2', medium: 'P3', low: 'P4' };
const PRIORITY_MEANING: Record<string, string> = {
  critical: 'Critical — fix immediately',
  high: 'High — fix soon',
  medium: 'Medium — normal queue',
  low: 'Low — minor/cosmetic',
};
const STATUS_FILL: Record<string, string> = { Open: 'FFC00000', Resolved: 'FF70AD47' };
const PRIORITY_FILL: Record<string, string> = {
  critical: 'FFC00000',
  high: 'FFED7D31',
  medium: 'FFFFC000',
  low: 'FF70AD47',
};

/**
 * Styled Excel workbook modeled on a classic "Bug Tracker Dashboard" template
 * — plain white sheet, navy table header, colored Priority/Status badges, a
 * Priority Summary table, and bar + pie charts of the priority breakdown.
 * exceljs can't create native Excel chart objects in the browser (only embed
 * images), so both charts are pictures, not live/editable Excel charts.
 *
 * `priorityCounts` is passed in rather than derived from `rows` because
 * `rows` has one line per assignee (a ticket with 2 assignees appears
 * twice) — counting severities off it would double-count tickets in the
 * charts. The caller has the pre-flatMap ticket list, so it computes the
 * per-ticket distribution itself.
 */
export async function exportAssignedTicketsXLSX(
  rows: AssignedTicketExportRow[],
  priorityCounts: Record<string, number>,
  scopeLabel: string
) {
  const ExcelJS = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'AI QA Engineer';

  const ws = wb.addWorksheet('Bug Tracker');
  ws.columns = [
    { width: 6 }, // A S.No
    { width: 20 }, // B Website
    { width: 14 }, // C Bug ID
    { width: 22 }, // D Ticket Link
    { width: 42 }, // E Bug Title
    { width: 18 }, // F Assigned To
    { width: 10 }, // G Priority
    { width: 12 }, // H Status
  ];
  const LAST_COL = 8;

  // ---- Title ----
  ws.getCell(1, 1).value = '🐞 Bug Tracker Dashboard';
  ws.getCell(1, 1).font = { bold: true, size: 16, color: { argb: 'FF1F2937' } };
  ws.getCell(2, 1).value = `Sorted by Priority (P1 = highest) · Generated ${new Date().toLocaleString()} · ${scopeLabel} · ${rows.length} bug${rows.length === 1 ? '' : 's'}`;
  ws.getCell(2, 1).font = { italic: true, size: 9, color: { argb: 'FF6B7280' } };

  // ---- Main table ----
  const tableHeaderRow = 4;
  const headers = ['S.No', 'Website Name', 'Bug ID', 'Ticket Link', 'Bug Title / Description', 'Assigned To', 'Priority', 'Status'];
  headers.forEach((h, i) => {
    const cell = ws.getCell(tableHeaderRow, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F3864' } };
    cell.alignment = { vertical: 'middle' };
  });
  ws.getRow(tableHeaderRow).height = 20;

  rows.forEach((r, i) => {
    const row = tableHeaderRow + 1 + i;
    ws.getCell(row, 1).value = r.sNo;
    ws.getCell(row, 1).alignment = { horizontal: 'center' };
    ws.getCell(row, 2).value = r.website;
    ws.getCell(row, 3).value = r.repId;

    const linkCell = ws.getCell(row, 4);
    linkCell.value = { text: 'Open Ticket ↗', hyperlink: r.ticketUrl };
    linkCell.font = { color: { argb: 'FF2563EB' }, underline: true, size: 10 };

    ws.getCell(row, 5).value = r.title;

    ws.getCell(row, 6).value = r.assignedTo;

    const priorityCell = ws.getCell(row, 7);
    priorityCell.value = PRIORITY_LABEL[r.severity] || r.severity;
    priorityCell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    priorityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PRIORITY_FILL[r.severity] || 'FF9CA3AF' } };
    priorityCell.alignment = { horizontal: 'center' };

    const statusCell = ws.getCell(row, 8);
    statusCell.value = r.status === 'Resolved' ? 'Closed' : 'Open';
    statusCell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: STATUS_FILL[r.status] || 'FF9CA3AF' } };
    statusCell.alignment = { horizontal: 'center' };

    if (i % 2 === 1) {
      [1, 2, 3, 5, 6].forEach((c) => {
        ws.getCell(row, c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
      });
    }
    for (let c = 1; c <= LAST_COL; c++) {
      ws.getCell(row, c).border = { bottom: { style: 'hair', color: { argb: 'FFE5E7EB' } } };
    }
  });

  // ---- Priority Summary table ----
  const summaryHeaderRow = tableHeaderRow + rows.length + 3;
  ws.getCell(summaryHeaderRow - 1, 1).value = '📋 Priority Summary';
  ws.getCell(summaryHeaderRow - 1, 1).font = { bold: true, size: 12, color: { argb: 'FF1F2937' } };

  ['Priority', 'Meaning', 'Bug Count', '% of Total'].forEach((h, i) => {
    const cell = ws.getCell(summaryHeaderRow, i + 1);
    cell.value = h;
    cell.font = { bold: true };
    cell.border = { bottom: { style: 'thin', color: { argb: 'FF9CA3AF' } } };
  });

  const activePriorities = PRIORITY_ORDER.filter((p) => (priorityCounts[p] || 0) > 0);
  const totalTickets = activePriorities.reduce((s, p) => s + priorityCounts[p], 0) || 1;
  activePriorities.forEach((p, i) => {
    const row = summaryHeaderRow + 1 + i;
    const badge = ws.getCell(row, 1);
    badge.value = PRIORITY_LABEL[p];
    badge.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    badge.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PRIORITY_FILL[p] } };
    badge.alignment = { horizontal: 'center' };
    ws.getCell(row, 2).value = PRIORITY_MEANING[p];
    ws.getCell(row, 3).value = priorityCounts[p];
    ws.getCell(row, 3).alignment = { horizontal: 'center' };
    ws.getCell(row, 4).value = `${Math.round((priorityCounts[p] / totalTickets) * 100)}%`;
    ws.getCell(row, 4).alignment = { horizontal: 'center' };
  });
  const totalRow = summaryHeaderRow + 1 + activePriorities.length;
  ws.getCell(totalRow, 1).value = 'Total';
  ws.getCell(totalRow, 1).font = { bold: true };
  ws.getCell(totalRow, 3).value = totalTickets;
  ws.getCell(totalRow, 3).font = { bold: true };
  ws.getCell(totalRow, 3).alignment = { horizontal: 'center' };

  // ---- Charts (embedded images, placed beside the summary table) ----
  if (activePriorities.length) {
    const barSeries = activePriorities.map((p) => ({ label: PRIORITY_LABEL[p], value: priorityCounts[p], color: `#${PRIORITY_FILL[p].slice(2)}` }));
    const pieSeries = activePriorities.map((p) => ({ label: PRIORITY_LABEL[p], value: priorityCounts[p], color: `#${PRIORITY_FILL[p].slice(2)}` }));

    ws.getCell(summaryHeaderRow - 1, 6).value = 'Bug Count by Priority';
    ws.getCell(summaryHeaderRow - 1, 6).font = { bold: true, size: 11, color: { argb: 'FF1F2937' } };
    const barBuffer = await drawBarChartPNG(barSeries, 320, 220);
    const barImageId = wb.addImage({ buffer: barBuffer, extension: 'png' });
    ws.addImage(barImageId, { tl: { col: 5, row: summaryHeaderRow - 0.3 }, ext: { width: 320, height: 220 } });

    ws.getCell(summaryHeaderRow - 1, 10).value = 'Priority Distribution (%)';
    ws.getCell(summaryHeaderRow - 1, 10).font = { bold: true, size: 11, color: { argb: 'FF1F2937' } };
    const pieBuffer = await drawPieChartPNG(pieSeries, 220);
    const pieImageId = wb.addImage({ buffer: pieBuffer, extension: 'png' });
    ws.addImage(pieImageId, { tl: { col: 9, row: summaryHeaderRow - 0.3 }, ext: { width: 220, height: 220 } });
  }

  // ---- Second tab: focused Priority Summary view ----
  const ws2 = wb.addWorksheet('Priority Summary');
  ws2.columns = [{ width: 12 }, { width: 30 }, { width: 12 }, { width: 12 }];
  ws2.getCell(1, 1).value = '📋 Priority Summary';
  ws2.getCell(1, 1).font = { bold: true, size: 14, color: { argb: 'FF1F2937' } };
  ['Priority', 'Meaning', 'Bug Count', '% of Total'].forEach((h, i) => {
    const cell = ws2.getCell(3, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F3864' } };
  });
  activePriorities.forEach((p, i) => {
    const row = 4 + i;
    const badge = ws2.getCell(row, 1);
    badge.value = PRIORITY_LABEL[p];
    badge.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    badge.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PRIORITY_FILL[p] } };
    badge.alignment = { horizontal: 'center' };
    ws2.getCell(row, 2).value = PRIORITY_MEANING[p];
    ws2.getCell(row, 3).value = priorityCounts[p];
    ws2.getCell(row, 3).alignment = { horizontal: 'center' };
    ws2.getCell(row, 4).value = `${Math.round((priorityCounts[p] / totalTickets) * 100)}%`;
    ws2.getCell(row, 4).alignment = { horizontal: 'center' };
  });
  ws2.getCell(4 + activePriorities.length, 1).value = 'Total';
  ws2.getCell(4 + activePriorities.length, 1).font = { bold: true };
  ws2.getCell(4 + activePriorities.length, 3).value = totalTickets;
  ws2.getCell(4 + activePriorities.length, 3).font = { bold: true };

  const buf = await wb.xlsx.writeBuffer();
  downloadBlobObject(
    new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    `bug-tracker-${slug(scopeLabel)}.xlsx`
  );
}

export async function exportTicketListDocx(rows: TicketExportRow[], scopeLabel: string) {
  const branding = await fetchBrandingSafe();
  const logo = await fetchLogoAsset(branding.logoUrl);
  const brandColorHex = branding.primaryColor.replace(/^#/, '');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const children: any[] = [];

  const NO_BORDER = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  children.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: { top: NO_BORDER, bottom: NO_BORDER, left: NO_BORDER, right: NO_BORDER, insideHorizontal: NO_BORDER, insideVertical: NO_BORDER },
      rows: [
        new TableRow({
          children: [
            new TableCell({
              width: { size: 50, type: WidthType.PERCENTAGE },
              verticalAlign: VerticalAlign.CENTER,
              children: logo
                ? [new Paragraph({ children: [new ImageRun({ type: logo.type, data: logo.bytes, transformation: { width: branding.logoWidth, height: branding.logoHeight } })] })]
                : [new Paragraph({ text: '' })],
            }),
            new TableCell({
              width: { size: 50, type: WidthType.PERCENTAGE },
              verticalAlign: VerticalAlign.CENTER,
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [new TextRun({ text: branding.headerText, bold: true, size: branding.headerFontSize * 2, color: brandColorHex })],
                }),
              ],
            }),
          ],
        }),
      ],
    })
  );
  children.push(new Paragraph({ text: '', border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: brandColorHex, space: 4 } } }));
  children.push(new Paragraph({ text: '' }));

  children.push(new Paragraph({ text: `Tickets — ${scopeLabel}`, heading: HeadingLevel.HEADING_1 }));
  children.push(new Paragraph({ text: `Generated: ${new Date().toLocaleString()}  |  Total: ${rows.length}` }));
  children.push(new Paragraph({ text: '' }));

  children.push(
    makeTable(
      ['Ticket #', 'Title', 'Severity', 'Category', 'Status', 'Assigned To'],
      rows.map((r) => [r.repId, r.title, r.severity, r.category, r.status, r.assignees])
    )
  );

  children.push(new Paragraph({ text: '' }));
  children.push(
    new Paragraph({
      border: { top: { style: BorderStyle.SINGLE, size: 6, color: brandColorHex, space: 4 } },
      children: [new TextRun({ text: branding.footerText, italics: true, color: '888888', size: branding.footerFontSize * 2 })],
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  downloadBlobObject(blob, `tickets-${slug(scopeLabel)}.docx`);
}